# Travis Configuration for lecture-source-py code execution tests

sudo: false
language: python
dist: xenial

language: python

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - wget https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh -O anaconda3.sh
  - chmod +x anaconda3.sh
  - ./anaconda3.sh -b
  - export PATH=/home/travis/anaconda3/bin:$PATH

install:
  - pip install quantecon
  - pip install joblib
  - pip install sphinxcontrib-jupyter
  - make setup

script:
  - bash scripts/travis-coverage.sh
